name: XpringSDKDemo
options:
  bundleIdPrefix: io.xpring
targets:
  XRP-Demo:
    type: tool
    platform: macOS
    sources: [Sources/XRP]
    dependencies:
      - carthage: XpringKit
      - carthage: SwiftProtobuf
      - carthage: SwiftGRPC
    settings:
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks $(PROJECT_DIR)/Carthage/Build/Mac"
  ILP-Demo:
    type: tool
    platform: macOS
    sources: [Sources/ILP]
    dependencies:
      - carthage: XpringKit
      - carthage: SwiftProtobuf
      - carthage: SwiftGRPC
    settings:
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks $(PROJECT_DIR)/Carthage/Build/Mac"
  PayID-Demo:
    type: tool
    platform: macOS
    sources: [Sources/PayID]
    dependencies:
      - carthage: XpringKit
      - carthage: SwiftProtobuf
      - carthage: SwiftGRPC
    settings:
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks $(PROJECT_DIR)/Carthage/Build/Mac"

